#!/bin/bash
sterm=$1
result=`pacman --color=always -Ss "$1" | sed 's/installed: /installed:/g'`
preinfo=`echo "$result" | sed -n 1~2p | sed 's/\// /' | sed 's/([^)]*)//g' | sed -e 's/^[ ]*//' | sed 's/\x1B\[0m \x1B\[1;34m//g'`
IFS=$'\n' repos=( `echo "$preinfo" | awk '{print $1}';` )
IFS=$'\n' names=( `echo "$preinfo" | awk '{print $2}';` )
IFS=$'\n' pkgver=( `echo "$preinfo" | awk '{print $3}' | awk -F '-' '{$NF=""; print $0;}'` )
IFS=$'\n' pkgrel=( `echo "$preinfo" | awk '{print $3}' | awk -F '-' '{print $NF;}'` )
IFS=$'\n' pkgins=( `echo "$preinfo" | awk '{print $NF}' | sed 's/\[installed\]/*/' | sed 's/\[installed:.*\]/!/g' | sed '/\x1B\[1;32m[0-9].*/c\ '` )
IFS=$'\n' descs=( `echo "$result" | sed -n 2~2p | sed -e 's/^[ ]*//' | GREP_COLORS="ms=01;39:mc=01;39:sl=:cx=:fn=35:ln=32:bn=32:se=36" grep -iE --color=always "$1|"` )

for i in "${!names[@]}"; do
    printf "%16s \e[0m| %-40s \e[0m| %-18s %-6s \e[0m| %1s | %s\n" "${repos[i]}" "${names[i]}" "${pkgver[i]}" "${pkgrel[i]}" "${pkgins[i]}" "${descs[i]}"
done
